POST http://localhost:8080/graphql HTTP/1.1
Content-Type: application/json

{
    "query": "{  findById(arg0: 1) { id title } }"
}

###
GET http://localhost:8080/graphql/schema
Content-Type: application/json
